<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Dub\Models\Components;


class AnalyticsTopUrls
{
    /**
     * The destination URL
     *
     * @var string $url
     */
    #[\JMS\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * The number of clicks from this URL
     *
     * @var ?float $clicks
     */
    #[\JMS\Serializer\Annotation\SerializedName('clicks')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $clicks = null;

    /**
     * The number of leads from this URL
     *
     * @var ?float $leads
     */
    #[\JMS\Serializer\Annotation\SerializedName('leads')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $leads = null;

    /**
     * The number of sales from this URL
     *
     * @var ?float $sales
     */
    #[\JMS\Serializer\Annotation\SerializedName('sales')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $sales = null;

    /**
     * The total amount of sales from this URL, in cents
     *
     * @var ?float $saleAmount
     */
    #[\JMS\Serializer\Annotation\SerializedName('saleAmount')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $saleAmount = null;

    /**
     * @param  string  $url
     * @param  ?float  $clicks
     * @param  ?float  $leads
     * @param  ?float  $sales
     * @param  ?float  $saleAmount
     */
    public function __construct(string $url, ?float $clicks = 0, ?float $leads = 0, ?float $sales = 0, ?float $saleAmount = 0)
    {
        $this->url = $url;
        $this->clicks = $clicks;
        $this->leads = $leads;
        $this->sales = $sales;
        $this->saleAmount = $saleAmount;
    }
}